name: Deploy to S3 - Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: List current directory
      run:  ls -al

    - name: Deploy to S3 - Dev
      run: |
        aws s3 sync . s3://rahul-crc-use1-dev-frontend --delete --exclude ".github/*" --exclude ".git/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
